'use client'

import { useState } from 'react'
import { Play, ArrowDown, Send, ShieldAlert, Cpu } from 'lucide-react'

type ConsoleStep = 'input' | 'llm_call' | 'host_execute' | 'llm_final' | 'done'

export default function ToolExecutionConsole() {
  const [step, setStep] = useState<ConsoleStep>('input')
  const [logs, setLogs] = useState<string[]>([])

  const addLog = (msg: string) => {
    setLogs((prev) => [...prev, msg])
  }

  const startSimulation = async () => {
    setLogs([])

    // Step 1: Input
    setStep('input')
    addLog('✉️ [User]: "List open pull requests in mushfiqweb-next"')
    await wait(1500)

    // Step 2: LLM Tool Call
    setStep('llm_call')
    addLog('🧠 [LLM]: Decided to execute tool call. Emitting JSON representation:')
    addLog(
      JSON.stringify(
        {
          name: 'github/list_pull_requests',
          arguments: { repo: 'mushfiqweb-next', state: 'open' },
        },
        null,
        2
      )
    )
    await wait(2000)

    // Step 3: Host Execution
    setStep('host_execute')
    addLog('🖥️ [MCP Host]: Intercepted JSON. Checking permission sandbox...')
    addLog('✅ [MCP Host]: Verified safe. Querying github/list_pull_requests...')
    addLog('   - Tool Response Data:')
    addLog(
      JSON.stringify(
        [{ id: 493, title: 'feat: add MCP visualizer components', author: 'mushfiq' }],
        null,
        2
      )
    )
    await wait(2000)

    // Step 4: Final LLM synthesis
    setStep('llm_final')
    addLog('🧠 [LLM]: Tool response received. Synthesizing final answer...')
    await wait(1500)

    // Step 5: Done
    setStep('done')
    addLog(
      '🤖 [Claude]: I found 1 open pull request in mushfiqweb-next: "#493: feat: add MCP visualizer components" authored by @mushfiq.'
    )
  }

  const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

  return (
    <div className="my-8 rounded-2xl border border-gray-200 bg-white p-6 shadow-md dark:border-zinc-800 dark:bg-zinc-900/50">
      <div className="mb-6 flex flex-col items-start justify-between gap-4 border-b border-gray-100 pb-4 dark:border-zinc-800 md:flex-row md:items-center">
        <div>
          <h3 className="text-base font-bold text-gray-900 dark:text-zinc-100">
            Tool Calling & Execution Pipeline
          </h3>
          <p className="text-xs font-medium text-gray-500 dark:text-zinc-400">
            Observe how JSON parameters are generated by the model and executed by the local client
          </p>
        </div>
        <button
          onClick={startSimulation}
          disabled={step !== 'input' && step !== 'done'}
          className="flex items-center gap-1.5 rounded-lg bg-primary-600 px-4 py-2 text-xs font-bold text-white transition-colors hover:bg-primary-500 disabled:opacity-50"
        >
          <Play className="h-4 w-4" /> Trigger Tool Call
        </button>
      </div>

      <div className="grid grid-cols-1 gap-8 lg:grid-cols-12">
        {/* Left Side: Pipeline visual blocks */}
        <div className="flex flex-col justify-center space-y-4 rounded-xl bg-gray-50 p-6 dark:bg-zinc-800/40 lg:col-span-5">
          {/* User Input Block */}
          <div
            className={`rounded-lg border p-3 text-center transition-all ${
              step === 'input'
                ? 'border-primary-500 bg-primary-50 font-bold text-primary-700'
                : 'border-gray-200 bg-white text-gray-400 dark:border-zinc-800 dark:bg-zinc-900'
            }`}
          >
            <div className="text-xs">1. User Input</div>
          </div>

          <ArrowDown className="mx-auto h-4 w-4 text-gray-300" />

          {/* Model JSON Block */}
          <div
            className={`rounded-lg border p-3 text-center transition-all ${
              step === 'llm_call'
                ? 'border-indigo-500 bg-indigo-50 font-bold text-indigo-700'
                : 'border-gray-200 bg-white text-gray-400 dark:border-zinc-800 dark:bg-zinc-900'
            }`}
          >
            <div className="text-xs">2. LLM Emits Tool Schema</div>
          </div>

          <ArrowDown className="mx-auto h-4 w-4 text-gray-300" />

          {/* Client Execute Block */}
          <div
            className={`rounded-lg border p-3 text-center transition-all ${
              step === 'host_execute'
                ? 'border-amber-500 bg-amber-50 font-bold text-amber-700'
                : 'border-gray-200 bg-white text-gray-400 dark:border-zinc-800 dark:bg-zinc-900'
            }`}
          >
            <div className="text-xs">3. Client Executes Function</div>
          </div>

          <ArrowDown className="mx-auto h-4 w-4 text-gray-300" />

          {/* Final Answer Block */}
          <div
            className={`rounded-lg border p-3 text-center transition-all ${
              step === 'llm_final' || step === 'done'
                ? 'border-emerald-500 bg-emerald-50 font-bold text-emerald-700'
                : 'border-gray-200 bg-white text-gray-400 dark:border-zinc-800 dark:bg-zinc-900'
            }`}
          >
            <div className="text-xs">4. LLM Compiles Output</div>
          </div>
        </div>

        {/* Right Side: Log Console */}
        <div className="text-zinc-350 flex h-72 flex-col rounded-xl bg-zinc-950 p-4 font-mono text-[10.5px] lg:col-span-7">
          <div className="text-zinc-550 mb-2 border-b border-zinc-800 pb-1 text-[9.5px] uppercase tracking-wider">
            Console Payload Output
          </div>
          <div className="scrollbar-thin flex-1 space-y-2 overflow-y-auto whitespace-pre-wrap leading-normal">
            {logs.length === 0 ? (
              <div className="text-[10px] italic text-zinc-700">
                Click Trigger Tool Call to run pipeline simulation...
              </div>
            ) : (
              logs.map((line, idx) => {
                const isUser = line.startsWith('✉️')
                const isModel = line.startsWith('🧠') || line.startsWith('🤖')
                const isHost = line.startsWith('🖥️') || line.startsWith('✅')

                return (
                  <div
                    key={idx}
                    className={
                      isUser
                        ? 'font-bold text-blue-400'
                        : isModel
                          ? 'font-semibold text-purple-400'
                          : isHost
                            ? 'text-amber-400'
                            : 'text-zinc-300'
                    }
                  >
                    {line}
                  </div>
                )
              })
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
